apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-projeto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-projeto
  template:
    metadata:
      labels:
        app: app-projeto
    spec:
      containers:
      - name: app-projeto
        image: laranja1/app-projeto:317fd948dd82aa4975bfcac6f3ae029f592dbfe7
        ports:
        - containerPort: 80
