apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-projeto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-projeto
  template:
    metadata:
      labels:
        app: app-projeto
    spec:
      containers:
      - name: app-projeto
        image: laranja1/app-projeto:72849a7937972715476ef14cfa74a8de665fc68f

        ports:
        - containerPort: 80
