apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-projeto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-projeto
  template:
    metadata:
      labels:
        app: app-projeto
    spec:
      containers:
      - name: app-projeto
        image: laranja1/app-projeto:1ee94638d73839a262fc9c8b0290cb2bcc413393
        ports:
        - containerPort: 80
